eureka:
  client:
    service-url:
      defaultZone: http://idoc:idoc@localhost:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
spring:
  application:
    name: idoc-eureka
  security:
    user:
      password: idoc
      name: idoc
server:
  port: 8761
